WebApp/Models/Sections/ShowcaseViewModel.cs
using WebApp.Models.Components;

namespace WebApp.Models.Sections;

public class ShowcaseViewModel
{   
    public string? Id { get; set; }
    public ImageViewModel ShowcaseImage { get; set; } = null!;
    public string? Title { get; set; }
    public string? Text { get; set; }
    public LinkViewModel Link { get; set; } = new LinkViewModel();
    public string? BrandsText { get; set; }
    public List<ImageViewModel>? Brands { get; set; }
}

WebApp/Models/Sections/SubscribeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models.Sections;

public class SubscribeViewModel
{
    [Display(Name = "Daily Newsletter", Order = 0)]
    public bool NewsletterCheckbox1 { get; set; }

    [Display(Name = "Event Updates", Order = 1)]
    public bool NewsletterCheckbox2 { get; set; }

    [Display(Name = "Advertising Updates", Order = 2)]
    public bool NewsletterCheckbox3 { get; set; }

    [Display(Name = "Startups Weekly", Order = 3)]
    public bool NewsletterCheckbox4 { get; set; }

    [Display(Name = "Week in Review", Order = 4)]
    public bool NewsletterCheckbox5 { get; set; }

    [Display(Name = "Podcasts", Order = 5)]
    public bool NewsletterCheckbox6 { get; set; }

    [Display(Prompt = "     Your email", Order = 6)]
    [DataType(DataType.EmailAddress)]
    [Required(ErrorMessage = "Email is required")]
    public string Email { get; set; } = null!;
    public bool IsSubscribed { get; set; } = false;
}

WebApp/ViewModels/DontWantViewModel.cs
//using WebApp.Models;

//namespace WebApp.ViewModels;

//public class DontWantViewModel
//{
//    public string Title { get; set; } = "Subscribe*";
//    public DontWantModel Form { get; set; } = new DontWantModel();
//}




//using WebApp.Models;
//using WebApp.Models.Sections;

//namespace WebApp.ViewModels;

//public class DontWantViewModel
//{
//    public string Title { get; set; } = "Subscribe*";
//    public SubscribeViewModel Form { get; set; } = new SubscribeViewModel();
//}

WebApp/Controllers/SubscribersController.cs
using Infrastructure.Entities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics.Eventing.Reader;
using System.Text;
using WebApp.Models;
using WebApp.Models.Sections;

namespace WebApp.Controllers;

public class SubscribersController : Controller
{
    public IActionResult Index()
    {
        return View(new SubscribeViewModel());
    }

    [HttpPost]

    public async Task<IActionResult> Index(SubscribeViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            try
            {

                using var http = new HttpClient();
                var apiKey = "5e29b885-1414-4046-bb3c-33ac9c611b01";
                var url = $"https://localhost:7026/api/subscribers?key={apiKey}&email={viewModel.Email}&newsletterCheckbox1={viewModel.NewsletterCheckbox1}&newsletterCheckbox2={viewModel.NewsletterCheckbox2}&newsletterCheckbox3={viewModel.NewsletterCheckbox3}&newsletterCheckbox4={viewModel.NewsletterCheckbox4}&newsletterCheckbox5={viewModel.NewsletterCheckbox5}&newsletterCheckbox6={viewModel.NewsletterCheckbox6}&isSubscribed={viewModel.IsSubscribed}";

                var request = new HttpRequestMessage(HttpMethod.Post, url);
                var response = await http.SendAsync(request);

                if (response.IsSuccessStatusCode)
                {
                    TempData["Status"] = "Success";
                    viewModel.IsSubscribed = true;
                }

                else if (response.StatusCode == System.Net.HttpStatusCode.Conflict)
                {
                    TempData["Status"] = "AlreadyExist";
                }


                else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                {
                    TempData["Status"] = "Unauthorized";
                }

            }

            catch
            {
                TempData["Status"] = "ConnectionFailed";
            }

        }
        return RedirectToAction("Index", "Home", "dontWant");
    }



    //[HttpPost]

    //public async Task<IActionResult> Index(SubscribeViewModel viewModel)
    //{
    //    if (ModelState.IsValid)
    //    {
    //        try
    //        {

    //            using var http = new HttpClient();
    //            var apiKey = "5e29b885-1414-4046-bb3c-33ac9c611b01";
    //            var url = $"https://localhost:7026/api/subscribers?key={apiKey}&email={viewModel.Email}&newsletterCheckbox1={viewModel.NewsletterCheckbox1}&newsletterCheckbox2={viewModel.NewsletterCheckbox2}&newsletterCheckbox3={viewModel.NewsletterCheckbox3}&newsletterCheckbox4={viewModel.NewsletterCheckbox4}&newsletterCheckbox5={viewModel.NewsletterCheckbox5}&newsletterCheckbox6={viewModel.NewsletterCheckbox6}&isSubscribed={viewModel.IsSubscribed}";

    //            var request = new HttpRequestMessage(HttpMethod.Post, url);
    //            var response = await http.SendAsync(request);

    //            if (response.IsSuccessStatusCode)
    //            {
    //                ViewData["Status"] = "Success";
    //                viewModel.IsSubscribed = true;
    //                //return RedirectToAction("Index", "Home");
    //            }

    //            else if (response.StatusCode == System.Net.HttpStatusCode.Conflict)
    //            {
    //                ViewData["Status"] = "AlreadyExist";
    //            }


    //            else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
    //            {
    //                ViewData["Status"] = "Unauthorized";
    //            }

    //        }

    //        catch
    //        {
    //            ViewData["Status"] = "ConnectionFailed";
    //        }

    //    }

    //    return View(viewModel);
    //    //return RedirectToAction("Index", "Home");
    //}
}

WebApp/Controllers/UnsubscribeController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using WebApp.Models;
using WebApp.Models.Sections;

namespace WebApp.Controllers;

public class UnsubscribeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Index(UnsubscribeViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            try
            {
                using var http = new HttpClient();
                var apiKey = "5e29b885-1414-4046-bb3c-33ac9c611b01";
                var url = $"https://localhost:7026/api/subscribers?key={apiKey}&email={viewModel.Email}";
                var request = new HttpRequestMessage(HttpMethod.Delete, url);
                var response = await http.SendAsync(request);

                ViewData["StatusCode"] = (int)response.StatusCode;

                if (response.IsSuccessStatusCode)
                {
                    ViewData["Status"] = "Success";
                }
                else if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
                {
                    ViewData["Status"] = "NotFound";
                }
                else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                {
                    ViewData["Status"] = "Unauthorized";
                }
                else
                {
                    ViewData["Status"] = "ServerSent";
                }
            }
            catch
            {
                ViewData["Status"] = "ConnectionFailed";
            }
        }

        return View(viewModel);
    }

}

WebApp/Views/Sections/_DarkLight.cshtml
<section class="dark-light">
    <div class="dark-light-box">
        <div class="dark"></div>
        <div class="light"></div>
    </div>

    <div class="container black-box">
        <div class="text-h1">
            <h1 class="dark">Switch Between</h1>
            <h1 class="light">Ligh & Dark Mode</h1>
        </div>

        <div class="img-dark-light">
            <img src="images\dark-light.svg" alt="dark and light mode">
            <button class="round-button">
                <i class="fa-light fa-arrows-left-right"></i>
            </button>
        </div>
    </div>
</section>

WebApp/Views/Sections/_DontWant.cshtml
@using WebApp.Models
@model SubscribeViewModel

@{
    ViewData["Title"] = "Subscribe";
}

<div class="dontWant"">
    <div class="container">
       
        <div class="headning">
            <h1>Don't Want to Miss Anything?</h1>
            <img src="/images/Group.svg" alt="symbol of arrow">
        </div>

        <div class="contentSignUp">
            <form method="post" asp-controller="Subscribers" asp-action="Index" novalidate>
                 @*  <form method="post" asp-controller="Home" asp-action="Index" novalidate> *@
                <div class="contentSign">
                    <div class="column">
                        <h6>Sign up for <br> Newsletters</h6>
                    </div>
                        <div class="column">
                            <div class="input-group">
                                <input type = "checkbox" asp-for="NewsletterCheckbox1" />
                                <label asp-for="NewsletterCheckbox1">Daily Newsletter</label>
                            </div>
                                <span asp-validation-for="NewsletterCheckbox1"> </span>

                            <div class="input-group">
                                <input type="checkbox" asp-for="NewsletterCheckbox2" />
                                <label asp-for="NewsletterCheckbox2">Event Updates</label>
                            </div>
                                <span asp-validation-for="NewsletterCheckbox2"> </span>
                        </div>
                        
                        <div class="column">
                            <div class="input-group">
                                <input type="checkbox" asp-for="NewsletterCheckbox3" />
                                <label asp-for="NewsletterCheckbox3">Advertising Updates</label>
                            </div>
                                <span asp-validation-for="NewsletterCheckbox3"> </span>
                            <div class="input-group">
                                <input type="checkbox" asp-for="NewsletterCheckbox4" />
                                <label asp-for="NewsletterCheckbox4">Startups Weekly</label>
                            </div>
                                <span asp-validation-for="NewsletterCheckbox4"> </span>
                        </div>

                        <div class="column">
                            <div class="input-group">
                                <input type="checkbox" asp-for="NewsletterCheckbox5" />
                                <label asp-for="NewsletterCheckbox5">Week in Review</label>
                            </div class="input-group">
                                <span asp-validation-for="NewsletterCheckbox5"> </span>
                            <div class="input-group">
                                <input type="checkbox" asp-for="NewsletterCheckbox6" />
                                <label asp-for="NewsletterCheckbox6">Podcasts</label>
                            </div>
                                <span asp-validation-for="NewsletterCheckbox6"> </span>


                        </div>
                </div>

                <div class="contentEmail">
                    <div class="email">
                        <span id="envelope" class="envelope"><i class="fa fa-envelope"></i></span>
                        <div id="form-email" class="input-group">
                            @*<label asp-for="Form.Email"></label> *@
                            <span asp-validation-for="Email"> </span>
                            <input asp-for="Email"/>
                        </div>
                        <button id="form-submit" type="submit" class="btn-theme">Subscribe@* @Model.Title *@ </button>
                    </div>
                    
                    <div class="terms">
                        <p> <a href="#">*</a> Yes, I agree to the <a href="#">terms</a> and <a href="#">privacy policy</a>.</p>
                        <p><a asp-action="Index" asp-controller="Unsubscribe">Unsubscribe</a></p>
                    </div>

                </div>
            </form>
        </div>

        @if (TempData["Status"]?.ToString() == "Success")
        {
            <span class="alert alert-success">
                Thank you for subscribing!
            </span>
        }
        else if (TempData["Status"]?.ToString() == "AlreadyExist")
        {
            <span class="alert alert-warning">
                You have already subscribe!
            </span>
        }

        else if (TempData["Status"]?.ToString() == "Invalid")
        {
            <span class="alert alert-danger">
                You must enter a vaild email address!
            </span>
        }

        else if (TempData["Status"]?.ToString() == "ConnectionFailed")
        {
            <span class="alert alert-danger">
                Unable to contact the server. Please try again later.
            </span>
        }

            else if (TempData["Status"]?.ToString() == "Unauthorized")
        {
            <span class="alert alert-danger">
                An error occurred. Please contact web admin.
            </span>
        }

    </div>
</div>
<script defer src="~/js/validation.js"></script>

WebApp/Views/Sections/_Download.cshtml
<div class="download">
    <div class="container">
        <div class="phone">
            <img class="iPhonePro" src="/images/iPhonePro.svg" alt="">
            <img class="iPhoneProinside" src="/images/iPhoneProinside.svg" alt="">
        </div>

        <div class="contentinformation">
            <h1>Download Our App <br> for Any Devices:</h1>

            <div class="appstore">

                <div class="textappstore">
                    <p>App Store</p>
                    <div class="star">
                        <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i>
                    </div>
                    <h6>Editor's Choice</h6>
                    <p>rating 4.7, 187K+ reviews</p>
                </div>

                <div class="icon">
                    <a href="#"><img src="/images/icons/appstore.svg" alt="appstore icon"></a>
                </div>
            </div>

            <div class="googleplay">

                <div class="textgoogleplay">
                    <p>Google Play</p>
                    <div class="star">
                        <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i>
                    </div>
                    <h6>App of the Day</h6>
                    <p>rating 4.8, 30K+ reviews</p>
                </div>

                <div class="icon">
                    <a href="#"><img src="/images/icons/googleplay.svg" alt="googleplay icon"></a>
                </div>
            </div>
        </div>
    </div>
</div>

WebApp/Views/Sections/_Features.cshtml
@inject FeatureService _featureService
@{
    var result = await _featureService.GetAllFeaturesAsync();
    List<FeatureEntity> content = (List<FeatureEntity>)result.ContentResult!;
    var feature = content.First();
}

@if(content !=null){
<div class="features">
    <div class="container">
            <h1>@feature.Title</h1>
            <p>@feature.Ingress</p>
        <div class="tool-features">

                @foreach (var item in feature.FeaturesItems)
            {
                <div class="box">
                    <img src="images/icons/@item.ImageUrl" alt="">
                    <h5>@item.Title</h5>
                    <p>@item.Text</p>
                </div>
            }
        </div>
    </div>
</div>

}

WebApp/Views/Sections/_FooterPartial.cshtml
<footer>
    <div class="container">
        <div class="@((ViewContext.RouteData.Values["controller"] as string == "Auth") ? "d-none" : "social-media")">
            <a class="btn-social" href="#"><i class="fa-brands fa-facebook"></i></a>
            <a class="btn-social" href="#"><i class="fa-brands fa-square-x-twitter"></i></a>
            <a class="btn-social" href="#"><i class="fa-brands fa-instagram"></i></a>
            <a class="btn-social" href="#"><i class="fa-brands fa-youtube"></i></a>
        </div>
        <p>&copy; @DateTime.Now.Year Silicon. All rights reserved. <span>Pulvinar urna condimentum amet tempor, ornare integer. Lorem odio justo malesuada suspendisse viverra aliquet quisque turpis non. Feugiat in odio non nunc ornare consectetur.</span> </p>
    </div>
</footer>

WebApp/Views/Sections/_HeaderPartial.cshtml
@inject SignInManager<UserEntity> _signInManager
@inject UserManager<UserEntity> _userManager

@{
    var user = await _signInManager.UserManager.GetUserAsync(User);
    var ProfileImageUrl = user != null ? user.ProfileImageUrl : null;
}

@{
    var currentController = ViewContext.RouteData.Values["controller"]?.ToString();
    var currentAction = ViewContext.RouteData.Values["action"]?.ToString();
}

@{
    var themeMode = Context.Request.Cookies["ThemeMode"] ?? "light";
    var isDark = (themeMode == "dark") ? true : false;
}

<header class="header> @if (currentController == "Contact" && currentAction == "Index") {
 <text>gray-background</text>
 }">
    <div class="container">
        <a id="logo" asp-controller="Home" asp-action="Index"><img src="~/images/Silicon-Logotype -Light-Mode.svg" alt=""></a>

        <div id="menu">
            <nav>
                <a class="menu-link" asp-controller="Home" asp-action="Index" asp-fragment="overview">Overview</a>
                <a class="menu-link" asp-controller="Home" asp-action="Index" asp-fragment="features">Features</a>
                <a class="menu-link" asp-controller="Contact" asp-action="Index">Contact</a>

                @if (_signInManager.IsSignedIn(User))
                {
                    <a class="menu-link" asp-controller="Courses" asp-action="Index">Courses</a>
                }

            </nav>
        </div>

        <div class="btn-switch">
            <label>Light</label>
            <label class="switch" for="switch-mode">
                <input type="checkbox" id="switch-mode" checked="@isDark" />
                <span class="slider round"></span>
            </label>
            <label>Dark</label>
        </div>


        <div class="account-buttons">
            @if (_signInManager.IsSignedIn(User))
            {
                <a class="btn-gray" asp-controller="Auth" asp-action="SignOut"><i class="fa-light fa-right-to-bracket"></i><span>Sign Out</span></a>
                <div class="profile-img">
                    <a asp-controller="Account" asp-action="Details">
                        @if (user != null && !string.IsNullOrEmpty(user.ProfileImageUrl))
                        {
                            <img src="~/images/uploads/profiles/@user.ProfileImageUrl" alt="Profile image">
                        }
                        else
                        {
                            <img src="~/images/uploads/profiles/avatar.jpg" alt="Default Profile Image">
                        }
                    </a>
                </div>
            }

            else
            {
                <a class="btn-gray" asp-controller="Auth" asp-action="SignIn"><i class="fa-light fa-right-to-bracket"></i><span>Sign in</span></a>
                <a class="btn-theme" asp-controller="Auth" asp-action="SignUp"><i class="fa-regular fa-user"></i><span>Sign up</span></a>
            }

        </div>

        <div class="btn-mobile">
            <button class="btn" id="mobil-menu-btn"><i class="fa-solid fa-bars"></i></button>
        </div>

    </div>

    <div id="mobil-menu" class="wrapper" aria-expanded="false"/>

        <div class="account-buttons">
            @if (_signInManager.IsSignedIn(User))
            {
                <a class="btn-gray" asp-controller="Auth" asp-action="SignOut"><i class="fa-light fa-right-to-bracket"></i><span>Sign Out</span></a>
                <a class="btn-theme" asp-controller="Account" asp-action="Details">Details</a>
                <a class="btn-theme" asp-controller="Courses" asp-action="Index">Courses</a>
              
            }
            else
            {
                <a class="btn-gray" asp-controller="Auth" asp-action="SignIn"><i class="fa-light fa-right-to-bracket"></i><span>Sign in</span></a>
                <a class="btn-theme" asp-controller="Auth" asp-action="SignUp"><i class="fa-regular fa-user"></i><span>Sign up</span></a>
            }

            <div class="menu">
                <nav>
                    <a class="menu-link" href="#overview">Overview</a>
                    <a class="menu-link" href="#features">Featueres</a>
                    <a class="menu-link" asp-controller="Contact" asp-action="Index">Contact</a>
                </nav>
            </div>
        </div>
    </div>

    
</header>

WebApp/Views/Sections/_Integrate.cshtml
<div class="integrate">
    <div class="container">
        <h1>Integrate Top Work Tools</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin volutpat mollis egestas. Nam luctus <br> facilisis ultrices. Pellentesque volutpat ligula est. Mattis fermentum, at nec lacus.</p>
        <div class="tool-features">
            <div class="box">
                <img src="images/icons/super-g.svg" alt="">
                <p>Lorem magnis pretium sed curabitur nunc facilisi nunc cursus sagittis.</p>
            </div>
            <div class="box">
                <img src="/images/icons/Zoom.svg" alt="">
                <p>In eget a mauris quis. Tortor dui tempus quis integer est sit natoque placerat dolor.</p>
            </div>
            <div class="box">
                <img src="/images/icons/Slack.svg" alt="">
                <p>Id mollis consectetur congue egestas egestas suspendisse blandit justo.</p>
            </div>
            <div class="box">
                <img src="/images/icons/gmail.svg" alt="">
                <p>Rutrum interdum tortor, sed at nulla. A cursus bibendum elit purus cras praesent.</p>
            </div>
            <div class="box">
                <img src="/images/icons/Trello.svg" alt="">
                <p>Congue pellentesque amet, viverra curabitur quam diam scelerisque fermentum urna.</p>
            </div>
            <div class="box">
                <img src="/images/icons/MailChimp.svg" alt="">
                <p>A elementum, imperdiet enim, pretium etiam facilisi in aenean quam mauris.</p>
            </div>
            <div class="box">
                <img src="/images/icons/Dropbox.svg" alt="">
                <p>Ut in turpis consequat odio diam lectus elementum. Est faucibus blandit platea.</p>
            </div>
            <div class="box">
                <img src="/images/icons/Evernote.svg" alt="">
                <p>Faucibus cursus maecenas lorem cursus nibh. Sociis sit risus id. Sit facilisis dolor arcu.</p>
            </div>
        </div>
    </div>
</div>

WebApp/Views/Sections/_Manage.cshtml
<div class="manage">
    <div class="container">
        <div class="taskmaster">
            <img src="/images/Taskmaster.svg" alt="">
        </div>

        <div class="manageInfo">
            <h1>Manage Your Work</h1>
            <div class="managetext">
                <i class="fa-light fa-circle-check"></i>
                <p>Powerful project management</p>
            </div>
            <div class="managetext">
                <i class="fa-light fa-circle-check"></i>
                <p>Transparent work management</p>
            </div>
            <div class="managetext">
                <i class="fa-light fa-circle-check"></i>
                <p>Manage work & focus on the most important tasks</p>
            </div>
            <div class="managetext">
                <i class="fa-light fa-circle-check"></i>
                <p>Track your progress with interactive charts</p>
            </div>
            <div class="managetext">
                <i class="fa-light fa-circle-check"></i>
                <p>Easiest way to track time spent on tasks</p>
            </div>
            <a class="btn-theme-s" href="#">Learn more<i class="fa-regular fa-arrow-right"></i></a>
        </div>
    </div>
</div>

WebApp/Views/Sections/_Showcase.cshtml
@model ShowcaseViewModel

<section id="@Model.Id" class="showcase">
    <div class="container">
        <div class="content">
            <h1>@Model.Title</h1>
            <p>@Model.Text</p>
            <a class="btn-theme-s" asp-controller="@Model.Link.ControllerName" asp-action="@Model.Link.ActionName">@Model.Link.Text</a>
            <h6>@Model.BrandsText</h6>
            <div class="brands">
                @if (Model.Brands != null)
                {
                    foreach (var brand in Model.Brands)
                    {
                        <img src="@brand.ImageUrl" alt="@brand.AltText">
                    }
                })
            </div>
        </div>
    </div>
    <img class="backround-image" src="@Model.ShowcaseImage.ImageUrl" alt="@Model.ShowcaseImage.AltText">
</section>